# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore: github-actions"
      include: "scope"
    labels:
      - "dependency"
      - "status/0-triage"
      - "priority/p2"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore: npm"
      include: "scope"
    labels:
      - "dependency"
      - "status/0-triage"
      - "priority/p2"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: '@types/node'
        versions: '>=18.0.0'
