import {EmbeddingModel, LanguageModel} from "ai";
import {createOpenAI, OpenAIProvider} from "@ai-sdk/openai";
import {Provider} from '../provider';
import {RequestInit} from "../../types";

export class OpenRouter extends Provider {
    id = 'openrouter';
    name = 'OpenRouter';
    description = `A unified interface for LLMs. Find the best models & prices for your prompts.`;
    models = [
        {
            id: `${this.id}/nousresearch/deephermes-3-mistral-24b-preview:free`,
            name: 'Deephermes 3 Mistral 24b Preview',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 131078, embedding: 5120, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/arcee-ai/virtuoso-medium-v2`,
            name: 'Virtuoso Medium V2',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 151665, embedding: 5120, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000005000, output: 0.0000008000},
        },
        {
            id: `${this.id}/arcee-ai/arcee-blitz`,
            name: 'Arcee Blitz',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 131072, embedding: 5120, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000004500, output: 0.0000007500},
        },
        {
            id: `${this.id}/microsoft/phi-4-reasoning-plus:free`,
            name: 'Phi 4 Reasoning Plus',
            description: '',
            architecture: 'Phi3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 100352, embedding: 5120, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/microsoft/phi-4-reasoning-plus`,
            name: 'Phi 4 Reasoning Plus',
            description: '',
            architecture: 'Phi3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 100352, embedding: 5120, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000700, output: 0.0000003500},
        },
        {
            id: `${this.id}/microsoft/phi-4-reasoning:free`,
            name: 'Phi 4 Reasoning',
            description: '',
            architecture: 'Phi3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 100352, embedding: 5120, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwen3-1.7b:free`,
            name: 'Qwen 3 (1.7B)',
            description: '',
            architecture: 'Qwen3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 151936, embedding: 2048, input: 32000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwen3-4b:free`,
            name: 'Qwen 3 (4B)',
            description: '',
            architecture: 'Qwen3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 151936, embedding: 2560, input: 128000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/opengvlab/internvl3-14b:free`,
            name: 'InternVL 3 (14B)',
            description: '',
            architecture: 'InternVLChatModel',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 5120, input: 32000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/opengvlab/internvl3-2b:free`,
            name: 'InternVL 3 (2B)',
            description: '',
            architecture: 'InternVLChatModel',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 1536, input: 32000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/meta-llama/llama-guard-4-12b`,
            name: 'LLaMA Guard 4 (12B)',
            description: '',
            architecture: 'Llama4ForConditionalGeneration',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 163840, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000500, output: 0.0000000500},
        },
        {
            id: `${this.id}/qwen/qwen3-30b-a3b:free`,
            name: 'Qwen 3 (30B) A3b',
            description: '',
            architecture: 'Qwen3MoeForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 151936, embedding: 2048, input: 40960, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwen3-30b-a3b`,
            name: 'Qwen 3 (30B) A3b',
            description: '',
            architecture: 'Qwen3MoeForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 151936, embedding: 2048, input: 40960, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001000, output: 0.0000003000},
        },
        {
            id: `${this.id}/qwen/qwen3-8b:free`,
            name: 'Qwen 3 (8B)',
            description: '',
            architecture: 'Qwen3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 151936, embedding: 4096, input: 40960, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwen3-8b`,
            name: 'Qwen 3 (8B)',
            description: '',
            architecture: 'Qwen3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 151936, embedding: 4096, input: 128000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000350, output: 0.0000001380},
        },
        {
            id: `${this.id}/qwen/qwen3-14b:free`,
            name: 'Qwen 3 (14B)',
            description: '',
            architecture: 'Qwen3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 151936, embedding: 5120, input: 40960, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwen3-14b`,
            name: 'Qwen 3 (14B)',
            description: '',
            architecture: 'Qwen3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 151936, embedding: 5120, input: 40960, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000700, output: 0.0000002400},
        },
        {
            id: `${this.id}/qwen/qwen3-32b:free`,
            name: 'Qwen 3 (32B)',
            description: '',
            architecture: 'Qwen3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 151936, embedding: 5120, input: 40960, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwen3-32b`,
            name: 'Qwen 3 (32B)',
            description: '',
            architecture: 'Qwen3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 151936, embedding: 5120, input: 40960, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001000, output: 0.0000003000},
        },
        {
            id: `${this.id}/qwen/qwen3-235b-a22b:free`,
            name: 'Qwen 3 (235B) A22b',
            description: '',
            architecture: 'Qwen3MoeForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 151936, embedding: 4096, input: 40960, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwen3-235b-a22b`,
            name: 'Qwen 3 (235B) A22b',
            description: '',
            architecture: 'Qwen3MoeForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 151936, embedding: 4096, input: 40960, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001400, output: 0.0000006000},
        },
        {
            id: `${this.id}/tngtech/deepseek-r1t-chimera:free`,
            name: 'Deepseek R1 Chimera',
            description: '',
            architecture: 'DeepseekV3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 129280, embedding: 7168, input: 163840, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/thudm/glm-4-9b:free`,
            name: 'Glm 4 (9B)',
            description: '',
            architecture: 'ChatGLMModel',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 4096, input: 32000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/microsoft/mai-ds-r1:free`,
            name: 'Mai Ds R1',
            description: '',
            architecture: 'DeepseekV3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 129280, embedding: 7168, input: 163840, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/shisa-ai/shisa-v2-llama3.3-70b:free`,
            name: 'Shisa V2 (70B) LLaMA 3.3',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwen2.5-coder-7b-instruct`,
            name: 'Qwen 2.5 (7B) Coder Instruct',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 3584, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000100, output: 0.0000000300},
        },
        {
            id: `${this.id}/eleutherai/llemma_7b`,
            name: 'Llemma (7B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32016, embedding: 4096, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000012000},
        },
        {
            id: `${this.id}/alfredpros/codellama-7b-instruct-solidity`,
            name: 'Code LLaMA 7b Instruct Solidity',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32016, embedding: 4096, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000012000},
        },
        {
            id: `${this.id}/arliai/qwq-32b-arliai-rpr-v1:free`,
            name: 'QwQ v1 (32B) Arliai Rpr',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/agentica-org/deepcoder-14b-preview:free`,
            name: 'Deepcoder (14b) Preview',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 96000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/moonshotai/kimi-vl-a3b-thinking:free`,
            name: 'Kimi Vl A3b Thinking',
            description: '',
            architecture: 'KimiVLForConditionalGeneration',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 163840, embedding: 0, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/nvidia/llama-3.3-nemotron-super-49b-v1:free`,
            name: 'LLaMA 3.3 (49B) Nemotron Super V1',
            description: '',
            architecture: 'DeciLMForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/nvidia/llama-3.3-nemotron-super-49b-v1`,
            name: 'LLaMA 3.3 (49B) Nemotron Super V1',
            description: '',
            architecture: 'DeciLMForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001300, output: 0.0000004000},
        },
        {
            id: `${this.id}/all-hands/openhands-lm-32b-v0.1`,
            name: 'Openhands Lm V0.1 (32B) ',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 16384, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000026000, output: 0.0000034000},
        },
        {
            id: `${this.id}/scb10x/llama3.1-typhoon2-8b-instruct`,
            name: 'LLaMA 3.1 (8B) Typhoon2 Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001800, output: 0.0000001800},
        },
        {
            id: `${this.id}/scb10x/llama3.1-typhoon2-70b-instruct`,
            name: 'LLaMA 3.1 (70B) Typhoon2 Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008800, output: 0.0000008800},
        },
        {
            id: `${this.id}/qwen/qwen2.5-vl-3b-instruct:free`,
            name: 'Qwen VL 2.5 (3B) Instruct',
            description: '',
            architecture: 'Qwen2_5_VLForConditionalGeneration',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 151936, embedding: 2048, input: 64000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwen2.5-vl-32b-instruct:free`,
            name: 'Qwen VL 2.5 (32B)  Instruct',
            description: '',
            architecture: 'Qwen2_5_VLForConditionalGeneration',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwen2.5-vl-32b-instruct`,
            name: 'Qwen 2.5 VL (32B) Instruct',
            description: '',
            architecture: 'Qwen2_5_VLForConditionalGeneration',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 128000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000009000, output: 0.0000009000},
        },
        {
            id: `${this.id}/open-r1/olympiccoder-32b:free`,
            name: 'Olympiccoder (32B)',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/rekaai/reka-flash-3:free`,
            name: 'Reka Flash 3',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 100352, embedding: 6144, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/thedrummer/anubis-pro-105b-v1`,
            name: 'Anubis Pro V1 (105B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000010000},
        },
        {
            id: `${this.id}/thedrummer/skyfall-36b-v2`,
            name: 'Skyfall V2 (36B)',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 131072, embedding: 5120, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000005000, output: 0.0000008000},
        },
        {
            id: `${this.id}/microsoft/phi-4-multimodal-instruct`,
            name: 'Phi 4 Multimodal Instruct',
            description: '',
            architecture: 'Phi4MMForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 200064, embedding: 3072, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000500, output: 0.0000001000},
        },
        {
            id: `${this.id}/qwen/qwq-32b:free`,
            name: 'QwQ (32B)',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 40000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwq-32b`,
            name: 'QwQ (32B)',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001500, output: 0.0000002000},
        },
        {
            id: `${this.id}/moonshotai/moonlight-16b-a3b-instruct:free`,
            name: 'Moonlight (16B) A3b Instruct',
            description: '',
            architecture: 'DeepseekV3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 163840, embedding: 2048, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/nousresearch/deephermes-3-llama-3-8b-preview:free`,
            name: 'Deephermes 3 LLaMA 3 8b Preview',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/cognitivecomputations/dolphin3.0-r1-mistral-24b:free`,
            name: 'Dolphin 3.0 (24B) R1 Mistral',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 131074, embedding: 5120, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/cognitivecomputations/dolphin3.0-mistral-24b:free`,
            name: 'Dolphin 3.0 (24B) Mistral',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 131074, embedding: 5120, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/meta-llama/llama-guard-3-8b`,
            name: 'LLaMA Guard 3 (8B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000200, output: 0.0000000600},
        },
        {
            id: `${this.id}/aion-labs/aion-rp-llama-3.1-8b`,
            name: 'Aion Rp (8B) LLaMA 3.1',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002000, output: 0.0000002000},
        },
        {
            id: `${this.id}/qwen/qwen2.5-vl-72b-instruct:free`,
            name: 'Qwen 2.5 (72B) Vl Instruct',
            description: '',
            architecture: 'Qwen2_5_VLForConditionalGeneration',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 8192, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwen2.5-vl-72b-instruct`,
            name: 'Qwen 2.5 VL (72B) Instruct',
            description: '',
            architecture: 'Qwen2_5_VLForConditionalGeneration',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 8192, input: 32000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002500, output: 0.0000007500},
        },
        {
            id: `${this.id}/microsoft/phi-4`,
            name: 'Phi 4',
            description: '',
            architecture: 'Phi3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 100352, embedding: 5120, input: 16384, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000700, output: 0.0000001400},
        },
        {
            id: `${this.id}/sao10k/l3.3-euryale-70b`,
            name: 'Euryale V2  (70B) LLaMA 3.3',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000007000, output: 0.0000008000},
        },
        {
            id: `${this.id}/eva-unit-01/eva-llama-3.33-70b`,
            name: 'Eva V0.1 (70B) LLaMA 3.3 ',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 16384, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000040000, output: 0.0000060000},
        },
        {
            id: `${this.id}/meta-llama/llama-3.3-70b-instruct:free`,
            name: 'LLaMA 3.3 (70B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 8000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/meta-llama/llama-3.3-70b-instruct`,
            name: 'LLaMA 3.3 (70B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000800, output: 0.0000002500},
        },
        {
            id: `${this.id}/qwen/qwq-32b-preview:free`,
            name: 'QwQ (32B) (Preview)',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 16384, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwq-32b-preview`,
            name: 'QwQ (32B) (Preview)',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000900, output: 0.0000002700},
        },
        {
            id: `${this.id}/eva-unit-01/eva-qwen-2.5-72b`,
            name: 'Eva V0.2 (72B) Qwen 2.5',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 8192, input: 16384, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000040000, output: 0.0000060000},
        },
        {
            id: `${this.id}/infermatic/mn-inferor-12b`,
            name: 'Mn Inferor v0.1 (12B)',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 131072, embedding: 5120, input: 16384, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000012000},
        },
        {
            id: `${this.id}/qwen/qwen-2.5-coder-32b-instruct:free`,
            name: 'Qwen 2.5 (32B) Coder Instruct',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwen-2.5-coder-32b-instruct`,
            name: 'Qwen 2.5 (32B) Coder Instruct',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000600, output: 0.0000001500},
        },
        {
            id: `${this.id}/raifle/sorcererlm-8x22b`,
            name: 'SorcererLM 16 (8X22B) Bf',
            description: '',
            architecture: 'MixtralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 6144, input: 16000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000045000, output: 0.0000045000},
        },
        {
            id: `${this.id}/eva-unit-01/eva-qwen-2.5-32b`,
            name: 'Eva Qwen 2.5 (32B) V0.2',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 16384, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000026000, output: 0.0000034000},
        },
        {
            id: `${this.id}/thedrummer/unslopnemo-12b`,
            name: 'UnslopNemo v4.1 (12B)',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 131072, embedding: 5120, input: 32000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000004500, output: 0.0000004500},
        },
        {
            id: `${this.id}/anthracite-org/magnum-v4-72b`,
            name: 'Magnum v4 (72B)',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 8192, input: 16384, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000015000, output: 0.0000022500},
        },
        {
            id: `${this.id}/qwen/qwen-2.5-7b-instruct:free`,
            name: 'Qwen 2.5 (7B) Instruct',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 3584, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwen-2.5-7b-instruct`,
            name: 'Qwen 2.5 (7B) Instruct',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 3584, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000500, output: 0.0000001000},
        },
        {
            id: `${this.id}/nvidia/llama-3.1-nemotron-70b-instruct`,
            name: 'LLaMA 3.1 (70B) Nemotron Instruct Hugging Face',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001200, output: 0.0000003000},
        },
        {
            id: `${this.id}/thedrummer/rocinante-12b`,
            name: 'Rocinante v1.1 (12B)',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 131072, embedding: 5120, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002500, output: 0.0000005000},
        },
        {
            id: `${this.id}/anthracite-org/magnum-v2-72b`,
            name: 'Magnum v2 (72B)',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 8192, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000030000, output: 0.0000030000},
        },
        {
            id: `${this.id}/meta-llama/llama-3.2-3b-instruct:free`,
            name: 'LLaMA 3.2 (3B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 3072, input: 20000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/meta-llama/llama-3.2-3b-instruct`,
            name: 'LLaMA 3.2 (3B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 3072, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000100, output: 0.0000000200},
        },
        {
            id: `${this.id}/meta-llama/llama-3.2-1b-instruct:free`,
            name: 'LLaMA 3.2 (1B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 2048, input: 131000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/meta-llama/llama-3.2-1b-instruct`,
            name: 'LLaMA 3.2 (1B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 2048, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000050, output: 0.0000000100},
        },
        {
            id: `${this.id}/qwen/qwen-2.5-72b-instruct:free`,
            name: 'Qwen 2.5 (72B) Instruct',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 8192, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwen-2.5-72b-instruct`,
            name: 'Qwen 2.5 (72B) Instruct',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 8192, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001200, output: 0.0000003900},
        },
        {
            id: `${this.id}/sao10k/l3.1-euryale-70b`,
            name: 'Euryale V2.2 (70B) LLaMa 3 1',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000007000, output: 0.0000008000},
        },
        {
            id: `${this.id}/microsoft/phi-3.5-mini-128k-instruct`,
            name: 'Phi 3.5 Mini Instruct',
            description: '',
            architecture: 'Phi3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32064, embedding: 3072, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000300, output: 0.0000000900},
        },
        {
            id: `${this.id}/nousresearch/hermes-3-llama-3.1-70b`,
            name: 'Hermes 3 (70B) LLaMA 3.1',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001200, output: 0.0000003000},
        },
        {
            id: `${this.id}/nousresearch/hermes-3-llama-3.1-405b`,
            name: 'Hermes 3 (405B) LLaMA 3.1',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 16384, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000008000},
        },
        {
            id: `${this.id}/sao10k/l3-lunaris-8b`,
            name: 'Lunaris v1 (8B) LLaMa3',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000200, output: 0.0000000500},
        },
        {
            id: `${this.id}/meta-llama/llama-3.1-405b:free`,
            name: 'LLaMA 3.1 (405B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 16384, input: 64000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/meta-llama/llama-3.1-405b`,
            name: 'LLaMA 3.1 (405B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 16384, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000020000, output: 0.0000020000},
        },
        {
            id: `${this.id}/nothingiisreal/mn-celeste-12b`,
            name: 'Mn v1.9 (12B) Celeste',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 131072, embedding: 5120, input: 16384, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000012000},
        },
        {
            id: `${this.id}/meta-llama/llama-3.1-8b-instruct:free`,
            name: 'LLaMA 3.1 (8B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/meta-llama/llama-3.1-8b-instruct`,
            name: 'LLaMA 3.1 (8B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 16384, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000200, output: 0.0000000300},
        },
        {
            id: `${this.id}/meta-llama/llama-3.1-405b-instruct`,
            name: 'LLaMA 3.1 (405B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 16384, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000008000},
        },
        {
            id: `${this.id}/meta-llama/llama-3.1-70b-instruct`,
            name: 'LLaMA 3.1 (70B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001000, output: 0.0000002800},
        },
        {
            id: `${this.id}/sao10k/l3-euryale-70b`,
            name: 'Euryale v2.1 (70B) LLaMa3',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000014800, output: 0.0000014800},
        },
        {
            id: `${this.id}/cognitivecomputations/dolphin-mixtral-8x22b`,
            name: 'Dolphin 2.9 (8X22B) Mixtral',
            description: '',
            architecture: 'MixtralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32002, embedding: 6144, input: 16000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000009000, output: 0.0000009000},
        },
        {
            id: `${this.id}/qwen/qwen-2-72b-instruct`,
            name: 'Qwen 2 (72B) Instruct',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 8192, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000009000, output: 0.0000009000},
        },
        {
            id: `${this.id}/nousresearch/hermes-2-pro-llama-3-8b`,
            name: 'Hermes 2 (8B) Pro LLaMA 3',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128288, embedding: 4096, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000250, output: 0.0000000400},
        },
        {
            id: `${this.id}/microsoft/phi-3-mini-128k-instruct`,
            name: 'Phi 3 Mini Instruct',
            description: '',
            architecture: 'Phi3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32064, embedding: 3072, input: 128000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001000, output: 0.0000001000},
        },
        {
            id: `${this.id}/microsoft/phi-3-medium-128k-instruct`,
            name: 'Phi 3 Medium Instruct',
            description: '',
            architecture: 'Phi3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32064, embedding: 5120, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001000, output: 0.0000003000},
        },
        {
            id: `${this.id}/neversleep/llama-3-lumimaid-70b`,
            name: 'LLaMA 3 (70B) Lumimaid',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000040000, output: 0.0000060000},
        },
        {
            id: `${this.id}/meta-llama/llama-guard-2-8b`,
            name: 'LLaMA Guard 2 (8B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002000, output: 0.0000002000},
        },
        {
            id: `${this.id}/allenai/olmo-7b-instruct`,
            name: 'OLMo (7B) Instruct',
            description: '',
            architecture: 'OLMoForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 50280, embedding: 0, input: 2048, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000800, output: 0.0000002400},
        },
        {
            id: `${this.id}/neversleep/llama-3-lumimaid-8b`,
            name: 'LLaMA 3 (8B) Lumimaid',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 24576, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000938, output: 0.0000007500},
        },
        {
            id: `${this.id}/sao10k/fimbulvetr-11b-v2`,
            name: 'Fimbulvetr V2 (11B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 4096, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000012000},
        },
        {
            id: `${this.id}/meta-llama/llama-3-8b-instruct`,
            name: 'LLaMA 3 (8B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000300, output: 0.0000000600},
        },
        {
            id: `${this.id}/meta-llama/llama-3-70b-instruct`,
            name: 'LLaMA 3 (70B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000003000, output: 0.0000004000},
        },
        {
            id: `${this.id}/sophosympatheia/midnight-rose-70b`,
            name: 'Midnight Rose v2.0 (70B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 8192, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000008000},
        },
        {
            id: `${this.id}/nousresearch/nous-hermes-2-mixtral-8x7b-dpo`,
            name: 'Nous Hermes 2 (8X7B) Mixtral DPO',
            description: '',
            architecture: 'MixtralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32002, embedding: 4096, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000006000, output: 0.0000006000},
        },
        {
            id: `${this.id}/neversleep/noromaid-20b`,
            name: 'Noromaid v0.1 (20B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 5120, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000007500, output: 0.0000015000},
        },
        {
            id: `${this.id}/undi95/toppy-m-7b`,
            name: 'Toppy M (7B)',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 4096, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000012000},
        },
        {
            id: `${this.id}/alpindale/goliath-120b`,
            name: 'Goliath (120B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 8192, input: 6144, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000065625, output: 0.0000093750},
        },
        {
            id: `${this.id}/jondurbin/airoboros-l2-70b`,
            name: 'Airoboros L2 (70B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 8192, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000005000, output: 0.0000005000},
        },
        {
            id: `${this.id}/pygmalionai/mythalion-13b`,
            name: 'Mythalion (13B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 5120, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000005625, output: 0.0000011250},
        },
        {
            id: `${this.id}/undi95/remm-slerp-l2-13b`,
            name: 'ReMM SLERP L2 (13B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 5120, input: 6144, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000005625, output: 0.0000011250},
        },
        {
            id: `${this.id}/gryphe/mythomax-l2-13b`,
            name: 'MythoMax L2 (13B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 5120, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000650, output: 0.0000000650},
        },
    ];
    default = {
        baseURL: 'https://openrouter.ai/api/v1',
        pricingURL: 'https://openrouter.ai/docs/models',
        manageAPIKeysURL: 'https://openrouter.ai/settings/keys',
        model: 'meta-llama/llama-3.2-3b-instruct:free',
    };

    create(init: RequestInit = {}): OpenAIProvider {
        return createOpenAI({name: this.name, baseURL: this.baseUrl(init.baseURL), apiKey: this.apiKey(init.apiKey), headers: init.headers});
    }

    languageModel(model: string, init: RequestInit = {}): LanguageModel {
        return this.create(init)(model);
    }

    embeddingModel(_model: string, _init: RequestInit = {}): EmbeddingModel<string> {
        throw new Error(`Provider ${this.name} does not support embeddings`);
    }
}