import {EmbeddingModel, LanguageModel} from "ai";
import {createOpenAI, OpenAIProvider} from "@ai-sdk/openai";
import {Provider} from '../provider';
import {RequestInit} from "../../types";

export class OpenRouter extends Provider {
    id = 'openrouter';
    name = 'OpenRouter';
    description = `A unified interface for LLMs. Find the best models & prices for your prompts.`;
    models = [
        {
            id: `${this.id}/microsoft/phi-4-multimodal-instruct`,
            name: 'Phi 4 Multimodal Instruct',
            description: '',
            architecture: 'Phi4MMForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 200064, embedding: 3072, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000700, output: 0.0000001400},
        },
        {
            id: `${this.id}/qwen/qwq-32b:free`,
            name: 'QwQ (32B) (free)',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwq-32b`,
            name: 'QwQ (32B)',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001200, output: 0.0000001800},
        },
        {
            id: `${this.id}/qwen/qwen2.5-32b-instruct`,
            name: 'Qwen 2.5 (32B) Instruct',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000007900, output: 0.0000007900},
        },
        {
            id: `${this.id}/moonshotai/moonlight-16b-a3b-instruct:free`,
            name: 'Moonlight 16b A3b Instruct (free)',
            description: '',
            architecture: 'DeepseekV3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 163840, embedding: 2048, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/nousresearch/deephermes-3-llama-3-8b-preview:free`,
            name: 'Deephermes 3 LLaMA 3 8b Preview (free)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/cognitivecomputations/dolphin3.0-r1-mistral-24b:free`,
            name: 'Dolphin 3.0 (24B) R1 Mistral (free)',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 131074, embedding: 5120, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/cognitivecomputations/dolphin3.0-mistral-24b:free`,
            name: 'Dolphin 3.0 (24B) Mistral (free)',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 131074, embedding: 5120, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/meta-llama/llama-guard-3-8b`,
            name: 'LLaMA Guard 3 (8B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002000, output: 0.0000002000},
        },
        {
            id: `${this.id}/allenai/llama-3.1-tulu-3-405b`,
            name: 'LLaMA 3.1 (405B) Tulu 3',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128264, embedding: 16384, input: 16000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000050000, output: 0.0000100000},
        },
        {
            id: `${this.id}/aion-labs/aion-rp-llama-3.1-8b`,
            name: 'Aion Rp LLaMA 3.1 8b',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002000, output: 0.0000002000},
        },
        {
            id: `${this.id}/qwen/qwen2.5-vl-72b-instruct:free`,
            name: 'Qwen 2.5 (72B) Vl Instruct (free)',
            description: '',
            architecture: 'Qwen2_5_VLForConditionalGeneration',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 8192, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwen2.5-vl-72b-instruct`,
            name: 'Qwen 2.5 (72B) Vl Instruct',
            description: '',
            architecture: 'Qwen2_5_VLForConditionalGeneration',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 8192, input: 32000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000007000, output: 0.0000007000},
        },
        {
            id: `${this.id}/sophosympatheia/rogue-rose-103b-v0.2:free`,
            name: 'Rogue Rose 103b V0.2 (free)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 8192, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/microsoft/phi-4`,
            name: 'Phi 4',
            description: '',
            architecture: 'Phi3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 100352, embedding: 5120, input: 16384, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000700, output: 0.0000001400},
        },
        {
            id: `${this.id}/sao10k/l3.1-70b-hanami-x1`,
            name: 'L3 1 (70B) . Hanami X1',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 16000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000030000, output: 0.0000030000},
        },
        {
            id: `${this.id}/sao10k/l3.3-euryale-70b`,
            name: 'L3 3 (70B) . Euryale V2.3',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000007000, output: 0.0000008000},
        },
        {
            id: `${this.id}/eva-unit-01/eva-llama-3.33-70b`,
            name: 'Eva LLaMA 3.33 (70B) V0.1',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 16384, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000040000, output: 0.0000060000},
        },
        {
            id: `${this.id}/meta-llama/llama-3.3-70b-instruct:free`,
            name: 'LLaMA 3.3 (70B) Instruct (free)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/meta-llama/llama-3.3-70b-instruct`,
            name: 'LLaMA 3.3 (70B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001200, output: 0.0000003000},
        },
        {
            id: `${this.id}/qwen/qwq-32b-preview`,
            name: 'QwQ (32B) (Preview)',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002000, output: 0.0000002000},
        },
        {
            id: `${this.id}/eva-unit-01/eva-qwen-2.5-72b`,
            name: 'Eva Qwen 2.5 (72B) V0.2',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 8192, input: 32000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000007000, output: 0.0000007000},
        },
        {
            id: `${this.id}/infermatic/mn-inferor-12b`,
            name: 'Mn v0.1 (12B) Inferor',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 131072, embedding: 5120, input: 16384, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000012000},
        },
        {
            id: `${this.id}/qwen/qwen-2.5-coder-32b-instruct:free`,
            name: 'Qwen 2.5 (32B) Coder Instruct (free)',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 128000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwen-2.5-coder-32b-instruct`,
            name: 'Qwen 2.5 (32B) Coder Instruct',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 33000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000700, output: 0.0000001600},
        },
        {
            id: `${this.id}/raifle/sorcererlm-8x22b`,
            name: 'SorcererLM 16 (8X22B) Bf',
            description: '',
            architecture: 'MixtralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 6144, input: 16000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000045000, output: 0.0000045000},
        },
        {
            id: `${this.id}/eva-unit-01/eva-qwen-2.5-32b`,
            name: 'Eva Qwen 2.5 (32B) V0.2',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 16384, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000026000, output: 0.0000034000},
        },
        {
            id: `${this.id}/thedrummer/unslopnemo-12b`,
            name: 'UnslopNemo v4.1 (12B)',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 131072, embedding: 5120, input: 32000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000005000, output: 0.0000005000},
        },
        {
            id: `${this.id}/anthracite-org/magnum-v4-72b`,
            name: 'Magnum v4 (72B)',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 8192, input: 16384, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000018750, output: 0.0000022500},
        },
        {
            id: `${this.id}/qwen/qwen-2.5-7b-instruct`,
            name: 'Qwen 2.5 (7B) Instruct',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 3584, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000250, output: 0.0000000500},
        },
        {
            id: `${this.id}/nvidia/llama-3.1-nemotron-70b-instruct:free`,
            name: 'LLaMA 3.1 (70B) Nemotron Instruct Hugging Face (free)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/nvidia/llama-3.1-nemotron-70b-instruct`,
            name: 'LLaMA 3.1 (70B) Nemotron Instruct Hugging Face',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 131000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001200, output: 0.0000003000},
        },
        {
            id: `${this.id}/anthracite-org/magnum-v2-72b`,
            name: 'Magnum v2 (72B)',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 8192, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000030000, output: 0.0000030000},
        },
        {
            id: `${this.id}/thedrummer/rocinante-12b`,
            name: 'Rocinante v1.1 (12B)',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 131072, embedding: 5120, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002500, output: 0.0000005000},
        },
        {
            id: `${this.id}/meta-llama/llama-3.2-1b-instruct:free`,
            name: 'LLaMA 3.2 (1B) Instruct (free)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 2048, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/meta-llama/llama-3.2-1b-instruct`,
            name: 'LLaMA 3.2 (1B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 2048, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000100, output: 0.0000000100},
        },
        {
            id: `${this.id}/meta-llama/llama-3.2-3b-instruct`,
            name: 'LLaMA 3.2 (3B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 3072, input: 131000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000150, output: 0.0000000250},
        },
        {
            id: `${this.id}/qwen/qwen-2.5-72b-instruct`,
            name: 'Qwen 2.5 (72B) Instruct',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 8192, input: 128000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001300, output: 0.0000004000},
        },
        {
            id: `${this.id}/sao10k/l3.1-euryale-70b`,
            name: 'L3 1 (70B) . Euryale V2.2',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000007000, output: 0.0000008000},
        },
        {
            id: `${this.id}/ai21/jamba-1-5-large`,
            name: 'Ai21 Jamba 1.5 Large',
            description: '',
            architecture: 'JambaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 65536, embedding: 8192, input: 256000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000020000, output: 0.0000080000},
        },
        {
            id: `${this.id}/ai21/jamba-1-5-mini`,
            name: 'Ai21 Jamba 1.5 Mini',
            description: '',
            architecture: 'JambaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 65536, embedding: 4096, input: 256000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002000, output: 0.0000004000},
        },
        {
            id: `${this.id}/microsoft/phi-3.5-mini-128k-instruct`,
            name: 'Phi 3.5 Mini Instruct',
            description: '',
            architecture: 'Phi3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32064, embedding: 3072, input: 128000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001000, output: 0.0000001000},
        },
        {
            id: `${this.id}/nousresearch/hermes-3-llama-3.1-70b`,
            name: 'Hermes 3 (70B) LLaMA 3.1',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 131000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001200, output: 0.0000003000},
        },
        {
            id: `${this.id}/nousresearch/hermes-3-llama-3.1-405b`,
            name: 'Hermes 3 (405B) LLaMA 3.1',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 16384, input: 131000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000008000},
        },
        {
            id: `${this.id}/sao10k/l3-lunaris-8b`,
            name: 'L3 v1 (8B) Lunaris',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000300, output: 0.0000000600},
        },
        {
            id: `${this.id}/meta-llama/llama-3.1-405b`,
            name: 'LLaMA 3.1 (405B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 16384, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000020000, output: 0.0000020000},
        },
        {
            id: `${this.id}/nothingiisreal/mn-celeste-12b`,
            name: 'Mn v1.9 (12B) Celeste',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 131072, embedding: 5120, input: 16384, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000012000},
        },
        {
            id: `${this.id}/meta-llama/llama-3.1-8b-instruct:free`,
            name: 'LLaMA 3.1 (8B) Instruct (free)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/meta-llama/llama-3.1-8b-instruct`,
            name: 'LLaMA 3.1 (8B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000200, output: 0.0000000500},
        },
        {
            id: `${this.id}/meta-llama/llama-3.1-405b-instruct`,
            name: 'LLaMA 3.1 (405B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 16384, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000008000},
        },
        {
            id: `${this.id}/meta-llama/llama-3.1-70b-instruct`,
            name: 'LLaMA 3.1 (70B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001200, output: 0.0000003000},
        },
        {
            id: `${this.id}/qwen/qwen-2-7b-instruct:free`,
            name: 'Qwen 2 (7B) Instruct (free)',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 3584, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/qwen/qwen-2-7b-instruct`,
            name: 'Qwen 2 (7B) Instruct',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 3584, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000540, output: 0.0000000540},
        },
        {
            id: `${this.id}/sao10k/l3-euryale-70b`,
            name: 'L3 v2.1 (70B) Euryale',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000007000, output: 0.0000008000},
        },
        {
            id: `${this.id}/cognitivecomputations/dolphin-mixtral-8x22b`,
            name: 'Dolphin 2.9 (8X22B) .2 Mixtral',
            description: '',
            architecture: 'MixtralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32002, embedding: 6144, input: 16000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000009000, output: 0.0000009000},
        },
        {
            id: `${this.id}/qwen/qwen-2-72b-instruct`,
            name: 'Qwen 2 (72B) Instruct',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 8192, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000009000, output: 0.0000009000},
        },
        {
            id: `${this.id}/nousresearch/hermes-2-pro-llama-3-8b`,
            name: 'Hermes 2 (8B) Pro LLaMA 3',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128288, embedding: 4096, input: 131000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000250, output: 0.0000000400},
        },
        {
            id: `${this.id}/microsoft/phi-3-mini-128k-instruct:free`,
            name: 'Phi 3 Mini Instruct (free)',
            description: '',
            architecture: 'Phi3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32064, embedding: 3072, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/microsoft/phi-3-mini-128k-instruct`,
            name: 'Phi 3 Mini Instruct',
            description: '',
            architecture: 'Phi3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32064, embedding: 3072, input: 128000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001000, output: 0.0000001000},
        },
        {
            id: `${this.id}/microsoft/phi-3-medium-128k-instruct:free`,
            name: 'Phi 3 Medium Instruct (free)',
            description: '',
            architecture: 'Phi3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32064, embedding: 5120, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/microsoft/phi-3-medium-128k-instruct`,
            name: 'Phi 3 Medium Instruct',
            description: '',
            architecture: 'Phi3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32064, embedding: 5120, input: 128000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000010000, output: 0.0000010000},
        },
        {
            id: `${this.id}/neversleep/llama-3-lumimaid-70b`,
            name: 'LLaMA 3 (70B) Lumimaid',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000033750, output: 0.0000045000},
        },
        {
            id: `${this.id}/meta-llama/llama-guard-2-8b`,
            name: 'LLaMA Guard 2 (8B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002000, output: 0.0000002000},
        },
        {
            id: `${this.id}/neversleep/llama-3-lumimaid-8b`,
            name: 'LLaMA 3 (8B) Lumimaid',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 24576, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001875, output: 0.0000011250},
        },
        {
            id: `${this.id}/sao10k/fimbulvetr-11b-v2`,
            name: 'Fimbulvetr 11b V2',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 4096, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000012000},
        },
        {
            id: `${this.id}/meta-llama/llama-3-70b-instruct`,
            name: 'LLaMA 3 (70B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002300, output: 0.0000004000},
        },
        {
            id: `${this.id}/meta-llama/llama-3-8b-instruct:free`,
            name: 'LLaMA 3 (8B) Instruct (free)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/meta-llama/llama-3-8b-instruct`,
            name: 'LLaMA 3 (8B) Instruct',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000300, output: 0.0000000600},
        },
        {
            id: `${this.id}/databricks/dbrx-instruct`,
            name: 'DBRX Instruct',
            description: '',
            architecture: 'DbrxForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 100352, embedding: 0, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000012000, output: 0.0000012000},
        },
        {
            id: `${this.id}/sophosympatheia/midnight-rose-70b`,
            name: 'Midnight Rose v2.0 (70B) .3',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 8192, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000008000},
        },
        {
            id: `${this.id}/nousresearch/nous-hermes-2-mixtral-8x7b-dpo`,
            name: 'Nous Hermes 2 (8X7B) Mixtral DPO',
            description: '',
            architecture: 'MixtralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32002, embedding: 4096, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000006000, output: 0.0000006000},
        },
        {
            id: `${this.id}/cognitivecomputations/dolphin-mixtral-8x7b`,
            name: 'Dolphin 2.7 (8X7B) Mixtral',
            description: '',
            architecture: 'MixtralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32002, embedding: 4096, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000005000, output: 0.0000005000},
        },
        {
            id: `${this.id}/openchat/openchat-7b:free`,
            name: 'OpenChat 3.6 (8B) (free)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/openchat/openchat-7b`,
            name: 'OpenChat 3.6 (8B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 4096, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000550, output: 0.0000000550},
        },
        {
            id: `${this.id}/neversleep/noromaid-20b`,
            name: 'Noromaid v0.1 (20B) .1',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 5120, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000015000, output: 0.0000022500},
        },
        {
            id: `${this.id}/teknium/openhermes-2.5-mistral-7b`,
            name: 'OpenHermes 2.5 (7B) Mistral',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32002, embedding: 4096, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001700, output: 0.0000001700},
        },
        {
            id: `${this.id}/undi95/toppy-m-7b:free`,
            name: 'Toppy M (7B) (free)',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 4096, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/undi95/toppy-m-7b`,
            name: 'Toppy M (7B)',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 4096, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000700, output: 0.0000000700},
        },
        {
            id: `${this.id}/alpindale/goliath-120b`,
            name: 'Goliath (120B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 8192, input: 6144, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000093750, output: 0.0000093750},
        },
        {
            id: `${this.id}/jondurbin/airoboros-l2-70b`,
            name: 'Airoboros L2 3.1 (70B) .2',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 8192, input: 4000, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000005000, output: 0.0000005000},
        },
        {
            id: `${this.id}/xwin-lm/xwin-lm-70b`,
            name: 'Xwin-LM v0.1 (70B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 8192, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000037500, output: 0.0000037500},
        },
        {
            id: `${this.id}/pygmalionai/mythalion-13b`,
            name: 'Mythalion (13B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 5120, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000012000},
        },
        {
            id: `${this.id}/nousresearch/nous-hermes-llama2-13b`,
            name: 'Nous Hermes 2 (13B) LLaMA',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32032, embedding: 5120, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001800, output: 0.0000001800},
        },
        {
            id: `${this.id}/huggingfaceh4/zephyr-7b-beta:free`,
            name: 'Zephyr (7B) Beta (free)',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 4096, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/undi95/remm-slerp-l2-13b`,
            name: 'ReMM SLERP L2 (13B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 5120, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000012000},
        },
        {
            id: `${this.id}/gryphe/mythomax-l2-13b:free`,
            name: 'MythoMax L2 (13B) (free)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 5120, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/gryphe/mythomax-l2-13b`,
            name: 'MythoMax L2 (13B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 5120, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000650, output: 0.0000000650},
        },
        {
            id: `${this.id}/meta-llama/llama-2-13b-chat`,
            name: 'LLaMA 2 (13B) Chat Hugging Face',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 5120, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002200, output: 0.0000002200},
        },
    ];
    default = {
        baseURL: 'https://openrouter.ai/api/v1',
        pricingURL: 'https://openrouter.ai/docs/models',
        manageAPIKeysURL: 'https://openrouter.ai/settings/keys',
        model: 'meta-llama/llama-3.2-3b-instruct:free',
    };

    create(init: RequestInit = {}): OpenAIProvider {
        return createOpenAI({name: this.name, baseURL: this.baseUrl(init.baseURL), apiKey: this.apiKey(init.apiKey), headers: init.headers});
    }

    languageModel(model: string, init: RequestInit = {}): LanguageModel {
        return this.create(init)(model);
    }

    embeddingModel(_model: string, _init: RequestInit = {}): EmbeddingModel<string> {
        throw new Error(`Provider ${this.name} does not support embeddings`);
    }
}