import {EmbeddingModel, LanguageModel} from "ai";
import {createOpenAI, OpenAIProvider} from "@ai-sdk/openai";
import {Provider} from '../provider';
import {RequestInit} from "../../types";

export class OpenAI extends Provider {
    id = 'openai';
    name = 'OpenAI';
    description = `Abstract painting with vibrant pink and red tones dominating the composition. Soft streaks of yellow. Safety & Alignment.`;
    models = [
        {
            id: `${this.id}/gpt-4.5-preview`,
            name: 'GPT 4.5 Preview',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 0, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000750000, output: 0.0001500000},
        },
        {
            id: `${this.id}/gpt-4.1`,
            name: 'GPT 4.1',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 1047576, output: 32768},
                text: {input: true, output: true},
                image: {input: true, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000020000, output: 0.0000080000},
        },
        {
            id: `${this.id}/gpt-4.1-mini`,
            name: 'GPT 4.1 Mini',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 1047576, output: 32768},
                text: {input: true, output: true},
                image: {input: true, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000004000, output: 0.0000016000},
        },
        {
            id: `${this.id}/gpt-4.1-nano`,
            name: 'GPT 4.1 Nano',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 1047576, output: 32768},
                text: {input: true, output: true},
                image: {input: true, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001000, output: 0.0000004000},
        },
        {
            id: `${this.id}/gpt-4o`,
            name: 'GPT 4o',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 128000, output: 16385},
                text: {input: true, output: true},
                image: {input: true, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000025000, output: 0.0000100000},
        },
        {
            id: `${this.id}/gpt-4o-realtime-preview`,
            name: 'GPT 4o Realtime Preview',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 128000, output: 4096},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: true, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000050000, output: 0.0000200000},
        },
        {
            id: `${this.id}/gpt-4o-audio-preview`,
            name: 'GPT 4o Audio Preview',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 128000, output: 16385},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: true, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000025000, output: 0.0000100000},
        },
        {
            id: `${this.id}/gpt-4o-mini`,
            name: 'GPT 4o Mini',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 128000, output: 16385},
                text: {input: true, output: true},
                image: {input: true, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001500, output: 0.0000006000},
        },
        {
            id: `${this.id}/o4-mini`,
            name: 'o4 Mini',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 200000, output: 100000},
                text: {input: true, output: true},
                image: {input: true, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000011000, output: 0.0000044000},
        },
        {
            id: `${this.id}/o3-mini`,
            name: 'o3 Mini',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 200000, output: 100000},
                text: {input: true, output: true},
                image: {input: true, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000011000, output: 0.0000044000},
        },
        {
            id: `${this.id}/o1-pro`,
            name: 'o1 Pro',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 200000, output: 100000},
                text: {input: true, output: true},
                image: {input: true, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0001500000, output: 0.0006000000},
        },
        {
            id: `${this.id}/o1`,
            name: 'o1',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 200000, output: 100000},
                text: {input: true, output: true},
                image: {input: true, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000150000, output: 0.0000600000},
        },
        {
            id: `${this.id}/o1-mini`,
            name: 'o1 Mini',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 128000, output: 65536000},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000011000, output: 0.0000044000},
        },
        {
            id: `${this.id}/chatgpt-4o-latest`,
            name: 'ChatGPT 4o Latest',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 128000, output: 16385},
                text: {input: true, output: true},
                image: {input: true, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000050000, output: 0.0000150000},
        },
        {
            id: `${this.id}/gpt-4-turbo`,
            name: 'GPT 4 Turbo',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 128000, output: 4096},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000100000, output: 0.0000300000},
        },
        {
            id: `${this.id}/gpt-4-turbo-2024-04-09`,
            name: 'GPT 4 Turbo 2024 04 09',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 128000, output: 4096},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000100000, output: 0.0000300000},
        },
        {
            id: `${this.id}/gpt-4`,
            name: 'GPT 4',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 8192, output: 8192},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000300000, output: 0.0000600000},
        },
        {
            id: `${this.id}/gpt-4-1106-preview`,
            name: 'GPT 4 1106 Preview',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 128000, output: 4096},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000100000, output: 0.0000300000},
        },
        {
            id: `${this.id}/gpt-4-0125-preview`,
            name: 'GPT 4 0125 Preview',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 128000, output: 4096},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000100000, output: 0.0000300000},
        },
        {
            id: `${this.id}/gpt-3.5-turbo-instruct`,
            name: 'GPT 3.5 Turbo Instruct',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 4096, output: 4096},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000015000, output: 0.0000020000},
        },
        {
            id: `${this.id}/gpt-3.5-turbo`,
            name: 'GPT 3.5 Turbo',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 16384, output: 4096},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000030000, output: 0.0000060000},
        },
        {
            id: `${this.id}/gpt-3.5-turbo-16k`,
            name: 'GPT 3.5 Turbo 16k',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 16384, output: 4096},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000030000, output: 0.0000040000},
        },
        {
            id: `${this.id}/gpt-3.5-turbo-1106`,
            name: 'GPT 3.5 Turbo 1106',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 16384, output: 4096},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000010000, output: 0.0000020000},
        },
        {
            id: `${this.id}/gpt-3.5-turbo-0125`,
            name: 'GPT 3.5 Turbo 0125',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 16384, output: 4096},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000005000, output: 0.0000015000},
        },
        {
            id: `${this.id}/davinci-002`,
            name: 'Davinci 002',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 16385, output: 16_385},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000020000, output: 0.0000020000},
        },
        {
            id: `${this.id}/babbage-002`,
            name: 'Babbage 002',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 16385, output: 16_385},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000004000, output: 0.0000004000},
        },
        {
            id: `${this.id}/text-embedding-3-large`,
            name: 'Text Embedding 3 Large',
            description: '',
            architecture: '',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 3072, input: 8192, output: 0},
                text: {input: true, output: false},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001300, output: 0.0000000000},
        },
        {
            id: `${this.id}/text-embedding-3-small`,
            name: 'Text Embedding 3 Small',
            description: '',
            architecture: '',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 1536, input: 8192, output: 0},
                text: {input: true, output: false},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000200, output: 0.0000000000},
        },
        {
            id: `${this.id}/text-embedding-ada-002`,
            name: 'Text Embedding Ada 002',
            description: '',
            architecture: '',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 1536, input: 8192, output: 0},
                text: {input: true, output: false},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001000, output: 0.0000000000},
        },
    ];
    default = {
        baseURL: 'https://api.openai.com/v1',
        pricingURL: 'https://openai.com/api/pricing',
        manageAPIKeysURL: 'https://platform.openai.com/api-keys',
        model: `gpt-3.5-turbo-0125`,
    };

    create(init: RequestInit = {}): OpenAIProvider {
        return createOpenAI({
            name: this.name,
            baseURL: this.baseUrl(init.baseURL),
            apiKey: this.apiKey(init.apiKey),
            organization: init.organization,
            project: init.project,
            headers: init.headers
        });
    }

    languageModel(model: string, init: RequestInit = {}): LanguageModel {
        return this.create(init)(model);
    }

    embeddingModel(model: string, init: RequestInit = {}): EmbeddingModel<string> {
        return this.create(init).embedding(model)
    }
}