import {Provider} from '../../types';
import {EmbeddingModel, generateText, LanguageModel} from 'ai';
import {CohereProvider, createCohere} from '@ai-sdk/cohere';

export class Cohere extends Provider {
    id = 'cohere';
    name = 'Cohere';
    description = `Cohere is an AI platform for natural language processing that offers powerful language models for text generation and understanding.`;
    models = [
        {
            id: `${this.id}/command`,
            name: 'Command',
            description: `An instruction-following conversational model that performs language tasks with high quality, more reliably and with a longer context than our base generative models.`,
            architecture: 'CohereForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 4096, output: 4096},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000010000, output: 0.0000020000},
        },
        {
            id: `${this.id}/command-light`,
            name: 'Command Light',
            description: `A smaller, faster version of command. Almost as capable, but a lot faster.`,
            architecture: 'CohereForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 4096, output: 4096},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000003000, output: 0.0000006000},
        },
        {
            id: `${this.id}/command-r-08-2024`,
            name: 'Command R 08-2024 (32B)',
            description: `Command R 08-2024 is a research release of a 32 billion parameter highly performant generative model. Command R 08-2024 is a large language model with open weights optimized for a variety of use cases including reasoning, summarization, and question answering.`,
            architecture: 'CohereForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 256000, embedding: 8192, input: 131072, output: 4096},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001500, output: 0.0000006000},
        },
        {
            id: `${this.id}/command-r`,
            name: 'Command R (35B)',
            description: `Command-R is a research release of a 35 billion parameter highly performant generative model. Command-R is a large language model with open weights optimized for a variety of use cases including reasoning, summarization, and question answering.`,
            architecture: 'CohereForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 256000, embedding: 8192, input: 131072, output: 4096},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000005000, output: 0.0000015000},
        },
        {
            id: `${this.id}/command-r-plus-08-2024`,
            name: 'Command R+ 08-2024 (104B)',
            description: `Command R+ 08-2024 is an open weights research release of a 104 billion parameter model with highly advanced capabilities, this includes Retrieval Augmented Generation (RAG) and tool use to automate sophisticated tasks. The tool use in this model generation enables multi-step tool use which allows the model to combine multiple tools over multiple steps to accomplish difficult tasks.`,
            architecture: 'CohereForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 256000, embedding: 12288, input: 131072, output: 4096},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000025000, output: 0.0000100000},
        },
        {
            id: `${this.id}/command-r-plus`,
            name: 'Command R+ (104B)',
            description: `Command R+ is an open weights research release of a 104 billion parameter model with highly advanced capabilities, this includes Retrieval Augmented Generation (RAG) and tool use to automate sophisticated tasks. The tool use in this model generation enables multi-step tool use which allows the model to combine multiple tools over multiple steps to accomplish difficult tasks.`,
            architecture: 'CohereForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 256000, embedding: 12288, input: 131072, output: 4096},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000030000, output: 0.0000150000},
        },
        {
            id: `${this.id}/c4ai-aya-expanse-8b`,
            name: 'Aya Expanse (8B)',
            description: `Aya Expanse 8B is an open-weight research release of a model with highly advanced multilingual capabilities. It focuses on pairing a highly performant pre-trained Command family of models with the result of a year’s dedicated research from Cohere For AI, including data arbitrage, multilingual preference training, safety tuning, and model merging. The result is a powerful multilingual large language model.`,
            architecture: 'CohereForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 256000, embedding: 4096, input: 8192, output: 4096},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000005000, output: 0.0000015000},
        },
        {
            id: `${this.id}/c4ai-aya-expanse-32b`,
            name: 'Aya Expanse (32B)',
            description: `Aya Expanse 32B is an open-weight research release of a model with highly advanced multilingual capabilities. It focuses on pairing a highly performant pre-trained Command family of models with the result of a year’s dedicated research from Cohere For AI, including data arbitrage, multilingual preference training, safety tuning, and model merging. The result is a powerful multilingual large language model serving 23 languages.`,
            architecture: 'CohereForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 256000, embedding: 8192, input: 8192, output: 4096},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000005000, output: 0.0000015000},
        },
        {
            id: `${this.id}/embed-english-v3.0`,
            name: 'Embed English v3.0',
            description: `A model that allows for text to be classified or turned into embeddings. English only.`,
            architecture: '',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 124, input: 512, output: 0},
                text: {input: true, output: false},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001000, output: 0.0000000000},
        },
        {
            id: `${this.id}/embed-english-v3.0-image`,
            name: 'Embed English v3.0 Image',
            description: `A model that allows for text and images to be classified or turned into embeddings. English only.`,
            architecture: '',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 1024, input: 512, output: 0},
                text: {input: false, output: false},
                image: {input: true, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0001000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/embed-english-light-v3.0`,
            name: 'Embed English Light v3.0',
            description: `A smaller, faster version of embed-english-v3.0. Almost as capable, but a lot faster. English only.`,
            architecture: '',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 384, input: 512, output: 0},
                text: {input: true, output: false},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/embed-english-light-v3.0-image`,
            name: 'Embed English Light v3.0 Image',
            description: `A smaller, faster version of embed-english-v3.0. Almost as capable, but a lot faster. English only.`,
            architecture: '',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 384, input: 512, output: 0},
                text: {input: false, output: false},
                image: {input: true, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/embed-english-v2.0`,
            name: 'Embed English v2.0',
            description: `Allows for text to be classified or turned into embeddings. English only.`,
            architecture: '',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 4096, input: 512, output: 0},
                text: {input: true, output: false},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/embed-english-light-v2.0`,
            name: 'Embed English Light v2.0',
            description: `A smaller, faster version of embed-english-v2.0. Almost as capable, but a lot faster. English only.`,
            architecture: '',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 1024, input: 512, output: 0},
                text: {input: true, output: false},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/embed-multilingual-v3.0`,
            name: 'Embed Multilingual v3.0',
            description: `Provides multilingual classification and embedding support.`,
            architecture: '',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 1024, input: 512, output: 0},
                text: {input: true, output: false},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001000, output: 0.0000000000},
        },
        {
            id: `${this.id}/embed-multilingual-v3.0-image`,
            name: 'Embed Multilingual v3.0 Image',
            description: `Provides multilingual classification and embedding support.`,
            architecture: '',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 1024, input: 512, output: 0},
                text: {input: false, output: false},
                image: {input: true, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0001000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/embed-multilingual-light-v3.0`,
            name: 'Embed Multilingual Light v3.0',
            description: `A smaller, faster version of embed-multilingual-v3.0. Almost as capable, but a lot faster.`,
            architecture: '',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 384, input: 512, output: 0},
                text: {input: true, output: false},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/embed-multilingual-light-v3.0-image`,
            name: 'Embed Multilingual Light v3.0 Image',
            description: `A smaller, faster version of embed-multilingual-v3.0. Almost as capable, but a lot faster.`,
            architecture: '',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 384, input: 512, output: 0},
                text: {input: false, output: false},
                image: {input: true, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/embed-multilingual-v2.0`,
            name: 'Embed Multilingual v2.0',
            description: `Provides multilingual classification and embedding support.`,
            architecture: '',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 768, input: 256, output: 0},
                text: {input: true, output: false},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
    ];
    apiURL = 'https://api.cohere.ai/v2';
    pricingURL = 'https://cohere.com/pricing';

    create(apiKey: string): CohereProvider {
        return createCohere({baseURL: this.apiURL, apiKey: this.apiKey(apiKey)});
    }

    languageModel(model: string, apiKey: string = ''): LanguageModel {
        return this.create(apiKey)(model);
    }

    embeddingModel(model: string, apiKey: string = ''): EmbeddingModel<string> {
        return this.create(apiKey).embedding(model);
    }

    async check(apiKey: string) {
        try {
            await generateText({
                model: this.languageModel(apiKey, 'c4ai-aya-expanse-32b'),
                prompt: `hi`,
                maxTokens: 1,
            });

            return true;
        } catch (e) {
            return false;
        }
    }
}