import {Provider} from "../provider";
import {RequestInit} from "../../types";
import {EmbeddingModel, LanguageModel} from "ai";
import {createOpenAI, OpenAIProvider} from "@ai-sdk/openai";

export class Together extends Provider {
    id = 'together';
    name = 'Together';
    description = `Together is an AI platform for natural language processing that offers advanced models for text generation and understanding`;
    models = [
        {
            id: `${this.id}/meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo-p`,
            name: 'LLaMA 3.1 (8B) Instruct Turbo',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001800, output: 0.0000001800},
        },
        {
            id: `${this.id}/WhereIsAI/UAE-Large-V1`,
            name: 'Uae Large V1',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 0, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000160, output: 0.0000000160},
        },
        {
            id: `${this.id}/google/gemma-2-27b-it`,
            name: 'Gemma 2 (27B) Instruct',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000008000},
        },
        {
            id: `${this.id}/meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo`,
            name: 'LLaMA 3.1 (405B) Instruct Turbo',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 130815, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000035000, output: 0.0000035000},
        },
        {
            id: `${this.id}/meta-llama/Meta-Llama-3-70B-Instruct-Turbo`,
            name: 'LLaMA 3 (70B) Instruct Turbo',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008800, output: 0.0000008800},
        },
        {
            id: `${this.id}/BAAI/bge-large-en-v1.5`,
            name: 'BGE Large v1.5',
            description: '',
            architecture: '',
            capabilities: {
                embedding: true,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 512, input: 0, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000160, output: 0.0000000000},
        },
        {
            id: `${this.id}/Qwen/Qwen2-VL-72B-Instruct`,
            name: 'Qwen 2 (72B) Vl Instruct',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000012000, output: 0.0000012000},
        },
        {
            id: `${this.id}/mistralai/Mistral-7B-v0.1`,
            name: 'Mistral (7B)',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002000, output: 0.0000002000},
        },
        {
            id: `${this.id}/meta-llama/Llama-Vision-Free`,
            name: 'LLaMA Vision Free',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo`,
            name: 'LLaMA 3.2 (90B) Vision Instruct Turbo',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000012000, output: 0.0000012000},
        },
        {
            id: `${this.id}/meta-llama-llama-2-70b-hf`,
            name: 'LLaMA 2 (70B)',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000009000, output: 0.0000009000},
        },
        {
            id: `${this.id}/Gryphe/MythoMax-L2-13b`,
            name: 'MythoMax L2 (13B)',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000003000, output: 0.0000003000},
        },
        {
            id: `${this.id}/Qwen/Qwen2.5-72B-Instruct-Turbo`,
            name: 'Qwen 2.5 (72B) Instruct Turbo',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000012000, output: 0.0000012000},
        },
        {
            id: `${this.id}/meta-llama/Llama-3.3-70B-Instruct-Turbo-Free`,
            name: 'LLaMA 3.3 (70B) Instruct Turbo Free',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/mistralai/Mistral-Small-24B-Instruct-2501`,
            name: 'Mistral 25.01 (24B) Small Instruct',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000008000},
        },
        {
            id: `${this.id}/mistralai/Mixtral-8x22B-Instruct-v0.1`,
            name: 'Mixtral v0.1 (8X22B) Instruct',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 65536, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000012000, output: 0.0000012000},
        },
        {
            id: `${this.id}/meta-llama/Meta-Llama-3-8B-Instruct-Turbo`,
            name: 'LLaMA 3 (8B) Instruct Turbo',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001800, output: 0.0000001800},
        },
        {
            id: `${this.id}/NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO`,
            name: 'Nous Hermes 2 (8X7B) Mixtral DPO',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000006000, output: 0.0000006000},
        },
        {
            id: `${this.id}/meta-llama/LlamaGuard-2-8b`,
            name: 'LLaMA Guard 2 (8B)',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002000, output: 0.0000002000},
        },
        {
            id: `${this.id}/togethercomputer/m2-bert-80M-8k-retrieval`,
            name: 'M2 Bert Retrieval 8k',
            description: '',
            architecture: '',
            capabilities: {
                embedding: true,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 768, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000080, output: 0.0000000080},
        },
        {
            id: `${this.id}/meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo-classifier`,
            name: 'LLaMA 3.1 (8B) Instruct Turbo',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001800, output: 0.0000001800},
        },
        {
            id: `${this.id}/meta-llama/Llama-2-70b-hf`,
            name: 'LLaMA 2 (70B)',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000009000, output: 0.0000009000},
        },
        {
            id: `${this.id}/Qwen/Qwen2-72B-Instruct`,
            name: 'Qwen 2 (72B) Instruct',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000009000, output: 0.0000009000},
        },
        {
            id: `${this.id}/upstage/SOLAR-10.7B-Instruct-v1.0`,
            name: 'Upstage SOLAR v1 (11B) Instruct',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000003000, output: 0.0000003000},
        },
        {
            id: `${this.id}/togethercomputer/MoA-1`,
            name: 'Together Ai Moa 1',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/deepseek-ai/DeepSeek-R1-Distill-Llama-70B`,
            name: 'DeepSeek (70B) R1 Distill LLaMA',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000020000, output: 0.0000020000},
        },
        {
            id: `${this.id}/Qwen/QwQ-32B-Preview`,
            name: 'Qwen (32B) Qwq (Preview)',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000012000, output: 0.0000012000},
        },
        {
            id: `${this.id}/scb10x/scb10x-llama3-typhoon-v1-5x-4f316`,
            name: 'Typhoon 1.5x 70b Awq',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008800, output: 0.0000008800},
        },
        {
            id: `${this.id}/deepseek-ai/DeepSeek-V3-p-dp`,
            name: 'DeepSeek v3',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000012500, output: 0.0000012500},
        },
        {
            id: `${this.id}/mistralai/Mistral-7B-Instruct-v0.2`,
            name: 'Mistral v0.2 (7B) Instruct',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002000, output: 0.0000002000},
        },
        {
            id: `${this.id}/deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free`,
            name: 'DeepSeek (70B) R1 Distill LLaMA Free',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/togethercomputer/m2-bert-80M-2k-retrieval`,
            name: 'M2 Bert Retrieval 2k',
            description: '',
            architecture: '',
            capabilities: {
                embedding: true,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 768, input: 0, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000080, output: 0.0000000080},
        },
        {
            id: `${this.id}/meta-llama/Llama-3-8b-chat-hf`,
            name: 'LLaMA 3 (8B) Instruct Reference',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002000, output: 0.0000002000},
        },
        {
            id: `${this.id}/google/gemma-2b-it`,
            name: 'Gemma (2B) Instruct',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001000, output: 0.0000001000},
        },
        {
            id: `${this.id}/meta-llama/Meta-Llama-3-70B-Instruct-Lite`,
            name: 'LLaMA 3 (70B) Instruct Lite',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000005400, output: 0.0000005400},
        },
        {
            id: `${this.id}/meta-llama/Meta-Llama-3-8B-Instruct-Lite`,
            name: 'LLaMA 3 (8B) Instruct Lite',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001000, output: 0.0000001000},
        },
        {
            id: `${this.id}/Qwen/QwQ-32B`,
            name: 'Qwen (32B) Qwq',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000012000, output: 0.0000012000},
        },
        {
            id: `${this.id}/google/gemma-2-9b-it`,
            name: 'Gemma 2 (9B) Instruct',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000003000, output: 0.0000003000},
        },
        {
            id: `${this.id}/Gryphe/MythoMax-L2-13b-Lite`,
            name: 'Gryphe MythoMax L2 (13B) Lite',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001000, output: 0.0000001000},
        },
        {
            id: `${this.id}/scb10x/scb10x-llama3-1-typhoon2-60256`,
            name: 'Typhoon 2 70b Instruct',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008800, output: 0.0000008800},
        },
        {
            id: `${this.id}/scb10x/scb10x-llama3-1-typhoon-18370`,
            name: 'Typhoon 2 8b Instruct',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001800, output: 0.0000001800},
        },
        {
            id: `${this.id}/meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo`,
            name: 'LLaMA 3.1 (70B) Instruct Turbo',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008800, output: 0.0000008800},
        },
        {
            id: `${this.id}/meta-llama/Llama-3.3-70B-Instruct-Turbo`,
            name: 'LLaMA 3.3 (70B) Instruct Turbo',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008800, output: 0.0000008800},
        },
        {
            id: `${this.id}/meta-llama/Llama-2-7b-chat-hf`,
            name: 'LLaMA 2 (7B) Chat',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002000, output: 0.0000002000},
        },
        {
            id: `${this.id}/meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo`,
            name: 'LLaMA 3.1 (8B) Instruct Turbo',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001800, output: 0.0000001800},
        },
        {
            id: `${this.id}/BAAI/bge-base-en-v1.5`,
            name: 'BGE Base en v1.5',
            description: '',
            architecture: '',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 512, input: 512, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000080, output: 0.0000000080},
        },
        {
            id: `${this.id}/mistralai/Mixtral-8x7B-v0.1`,
            name: 'Mixtral v0.1 (8X7B)',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000006000, output: 0.0000006000},
        },
        {
            id: `${this.id}/deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B`,
            name: 'DeepSeek (1.5B) R1 Distill Qwen',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001800, output: 0.0000001800},
        },
        {
            id: `${this.id}/meta-llama/Meta-Llama-Guard-3-8B`,
            name: 'LLaMA Guard 3 (8B)',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002000, output: 0.0000002000},
        },
        {
            id: `${this.id}/meta-llama/Llama-2-13b-chat-hf`,
            name: 'LLaMA 2 (13B) Chat',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002200, output: 0.0000002200},
        },
        {
            id: `${this.id}/scb10x/scb10x-llama3-typhoon-v1-5-8b-instruct`,
            name: 'Typhoon 1.5 8b Instruct',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001800, output: 0.0000001800},
        },
        {
            id: `${this.id}/databricks/dbrx-instruct`,
            name: 'DBRX Instruct',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000012000, output: 0.0000012000},
        },
        {
            id: `${this.id}/nvidia/Llama-3.1-Nemotron-70B-Instruct-HF`,
            name: 'LLaMA 3.1 (70B) Nemotron Instruct Hugging Face',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008800, output: 0.0000008800},
        },
        {
            id: `${this.id}/Qwen/Qwen2.5-Coder-32B-Instruct`,
            name: 'Qwen 2.5 (32B) Coder Instruct',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 16384, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000008000},
        },
        {
            id: `${this.id}/microsoft/WizardLM-2-8x22B`,
            name: 'WizardLM 2 (8X22B)',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 65536, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000012000, output: 0.0000012000},
        },
        {
            id: `${this.id}/mistralai/Mistral-7B-Instruct-v0.3`,
            name: 'Mistral v0.3 (7B) Instruct',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002000, output: 0.0000002000},
        },
        {
            id: `${this.id}/Qwen/Qwen2.5-7B-Instruct-Turbo`,
            name: 'Qwen 2.5 (7B) Instruct Turbo',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000003000, output: 0.0000003000},
        },
        {
            id: `${this.id}/meta-llama/Llama-Guard-3-11B-Vision-Turbo`,
            name: 'LLaMA Guard 3 (11B) Vision Turbo',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001800, output: 0.0000001800},
        },
        {
            id: `${this.id}/meta-llama/Llama-3.2-3B-Instruct-Turbo`,
            name: 'LLaMA 3.2 (3B) Instruct Turbo',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000600, output: 0.0000000600},
        },
        {
            id: `${this.id}/meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo`,
            name: 'LLaMA 3.2 (11B) Vision Instruct Turbo',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001800, output: 0.0000001800},
        },
        {
            id: `${this.id}/deepseek-ai/DeepSeek-R1`,
            name: 'DeepSeek R1',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 163840, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000030000, output: 0.0000070000},
        },
        {
            id: `${this.id}/deepseek-ai/DeepSeek-V3`,
            name: 'DeepSeek v3',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000012500, output: 0.0000012500},
        },
        {
            id: `${this.id}/meta-llama/Llama-3-70b-chat-hf`,
            name: 'LLaMA 3 (70B) Instruct Reference',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008800, output: 0.0000008800},
        },
        {
            id: `${this.id}/mistralai/Mixtral-8x7B-Instruct-v0.1`,
            name: 'Mixtral v0.1 (8X7B) Instruct',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000006000, output: 0.0000006000},
        },
        {
            id: `${this.id}/togethercomputer/MoA-1-Turbo`,
            name: 'Together Ai Moa 1 Turbo',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B`,
            name: 'DeepSeek (14B) R1 Distill Qwen',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000016000, output: 0.0000016000},
        },
        {
            id: `${this.id}/mistralai/Mistral-7B-Instruct-v0.1`,
            name: 'Mistral (7B) Instruct',
            description: '',
            architecture: '',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002000, output: 0.0000002000},
        }
    ];
    default = {
        baseURL: 'https://api.together.xyz/v1',
        pricingURL: 'https://together.ai/pricing',
        manageAPIKeysURL: 'https://api.together.ai/settings/api-keys',
        model: `mistralai/Mistral-7B-Instruct-v0.1`,
    };

    create(init: RequestInit = {}): OpenAIProvider {
        return createOpenAI({name: this.name, baseURL: this.baseUrl(init.baseURL), apiKey: this.apiKey(init.apiKey), headers: init.headers});
    }

    languageModel(model: string, init: RequestInit = {}): LanguageModel {
        return this.create(init)(model);
    }

    embeddingModel(model: string, init: RequestInit = {}): EmbeddingModel<string> {
        return this.create(init).textEmbeddingModel(model);
    }
}