import {Provider} from "../provider";
import {RequestInit} from "../../types";
import {EmbeddingModel, LanguageModel} from "ai";
import {createOpenAI, OpenAIProvider} from "@ai-sdk/openai";

export class Together extends Provider {
    id = 'together';
    name = 'Together';
    description = `Together is an AI platform for natural language processing that offers advanced models for text generation and understanding`;
    models = [
        {
            id: `${this.id}/WhereIsAI/UAE-Large-V1`,
            name: 'Uae Large V1',
            description: '',
            architecture: 'BertModel',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 30522, embedding: 1024, input: 0, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000160, output: 0.0000000160},
        },
        {
            id: `${this.id}/Qwen/QwQ-32B`,
            name: 'Qwq (32B)',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000012000, output: 0.0000012000},
        },
        {
            id: `${this.id}/meta-llama/Llama-4-Scout-17B-16E-Instruct`,
            name: 'LLaMA 4 (16x17B) Scout Instruct',
            description: '',
            architecture: 'Llama4ForConditionalGeneration',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 1048576, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001800, output: 0.0000005900},
        },
        {
            id: `${this.id}/meta-llama/Llama-Guard-4-12B`,
            name: 'LLaMA Guard 4 (12B)',
            description: '',
            architecture: 'Llama4ForConditionalGeneration',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 1048576, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002000, output: 0.0000002000},
        },
        {
            id: `${this.id}/togethercomputer/m2-bert-80M-32k-retrieval`,
            name: 'M2 Bert (80M) 32k Retrieval',
            description: '',
            architecture: 'BertForSequenceClassification',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 30528, embedding: 768, input: 32768, output: 0},
                text: {input: true, output: false},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000080, output: 0.0000000000},
        },
        {
            id: `${this.id}/google/gemma-2-9b-it`,
            name: 'Gemma 2 (9B) Instruct',
            description: '',
            architecture: 'Gemma2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 256000, embedding: 3584, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000003000, output: 0.0000003000},
        },
        {
            id: `${this.id}/BAAI/bge-large-en-v1.5`,
            name: 'Bge Large En V1.5',
            description: '',
            architecture: 'BertModel',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 30522, embedding: 1024, input: 0, output: 0},
                text: {input: true, output: false},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000160, output: 0.0000000000},
        },
        {
            id: `${this.id}/deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free`,
            name: 'Deepseek R1 (70B) Distill LLaMA',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000000, output: 0.0000000000},
        },
        {
            id: `${this.id}/BAAI/bge-base-en-v1.5`,
            name: 'Bge Base En V1.5',
            description: '',
            architecture: 'BertModel',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 30522, embedding: 768, input: 512, output: 0},
                text: {input: true, output: false},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000080, output: 0.0000000000},
        },
        {
            id: `${this.id}/Gryphe/MythoMax-L2-13b`,
            name: 'MythoMax L2 (13B)',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 5120, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000003000, output: 0.0000003000},
        },
        {
            id: `${this.id}/deepseek-ai/DeepSeek-V3`,
            name: 'Deepseek v3',
            description: '',
            architecture: 'DeepseekV3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 129280, embedding: 7168, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000012500, output: 0.0000012500},
        },
        {
            id: `${this.id}/google/gemma-2-27b-it`,
            name: 'Gemma 2 (27B) Instruct',
            description: '',
            architecture: 'Gemma2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 256000, embedding: 4608, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000008000},
        },
        {
            id: `${this.id}/Qwen/Qwen2-VL-72B-Instruct`,
            name: 'Qwen 2 VL (72B) Instruct',
            description: '',
            architecture: 'Qwen2VLForConditionalGeneration',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 8192, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000012000, output: 0.0000012000},
        },
        {
            id: `${this.id}/togethercomputer/m2-bert-80M-8k-retrieval`,
            name: 'M2 Bert (80M) 8k Retrieval',
            description: '',
            architecture: 'BertForSequenceClassification',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 30528, embedding: 768, input: 8192, output: 0},
                text: {input: true, output: false},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000080, output: 0.0000000000},
        },
        {
            id: `${this.id}/togethercomputer/m2-bert-80M-2k-retrieval`,
            name: 'M2 Bert (80M) 2k Retrieval',
            description: '',
            architecture: 'BertForSequenceClassification',
            capabilities: {
                embedding: true,
                tool_call: false,
                rerank: false,
                features: [],
                size: {vocab: 30528, embedding: 768, input: 0, output: 0},
                text: {input: true, output: false},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000000080, output: 0.0000000000},
        },
        {
            id: `${this.id}/google/gemma-2b-it`,
            name: 'Gemma (2B) Instruct',
            description: '',
            architecture: 'GemmaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 256000, embedding: 2048, input: 8192, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001000, output: 0.0000001000},
        },
        {
            id: `${this.id}/deepseek-ai/DeepSeek-R1`,
            name: 'Deepseek R1',
            description: '',
            architecture: 'DeepseekV3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 129280, embedding: 7168, input: 163840, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000030000, output: 0.0000070000},
        },
        {
            id: `${this.id}/arcee-ai/arcee-blitz`,
            name: 'Arcee Blitz',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 131072, embedding: 5120, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000004500, output: 0.0000007500},
        },
        {
            id: `${this.id}/arcee-ai/virtuoso-medium-v2`,
            name: 'Virtuoso Medium V2',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 151665, embedding: 5120, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000005000, output: 0.0000008000},
        },
        {
            id: `${this.id}/meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8`,
            name: 'LLaMA 4 (128x17B) Maverick',
            description: '',
            architecture: 'Llama4ForConditionalGeneration',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 0, embedding: 0, input: 1048576, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002700, output: 0.0000008500},
        },
        {
            id: `${this.id}/Qwen/Qwen3-235B-A22B-fp8`,
            name: 'Qwen 3 (235B) A22b',
            description: '',
            architecture: 'Qwen3MoeForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 151936, embedding: 4096, input: 40960, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002000, output: 0.0000006000},
        },
        {
            id: `${this.id}/NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO`,
            name: 'Nous Hermes 2 (8X7B) Mixtral DPO',
            description: '',
            architecture: 'MixtralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32002, embedding: 4096, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000006000, output: 0.0000006000},
        },
        {
            id: `${this.id}/deepseek-ai/DeepSeek-R1-Distill-Llama-70B`,
            name: 'Deepseek R1 (70B) Distill LLaMA',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000020000, output: 0.0000020000},
        },
        {
            id: `${this.id}/deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B`,
            name: 'Deepseek R1 (1.5B) Distill Qwen',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 151936, embedding: 1536, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000001800, output: 0.0000001800},
        },
        {
            id: `${this.id}/mistralai/Mixtral-8x7B-v0.1`,
            name: 'Mixtral v0.1 (8X7B)',
            description: '',
            architecture: 'MixtralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 4096, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000006000, output: 0.0000006000},
        },
        {
            id: `${this.id}/mistralai/Mistral-7B-Instruct-v0.2`,
            name: 'Mistral v0.2 (7B) Instruct',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 4096, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002000, output: 0.0000002000},
        },
        {
            id: `${this.id}/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B`,
            name: 'Deepseek R1 (14B) Distill Qwen',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 131072, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000016000, output: 0.0000016000},
        },
        {
            id: `${this.id}/Qwen/Qwen2.5-Coder-32B-Instruct`,
            name: 'Qwen 2.5 (32B) Coder Instruct',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 5120, input: 16384, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008000, output: 0.0000008000},
        },
        {
            id: `${this.id}/Qwen/Qwen2-72B-Instruct`,
            name: 'Qwen 2 (72B) Instruct',
            description: '',
            architecture: 'Qwen2ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 8192, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000009000, output: 0.0000009000},
        },
        {
            id: `${this.id}/mistralai/Mixtral-8x7B-Instruct-v0.1`,
            name: 'Mixtral v0.1 (8X7B) Instruct',
            description: '',
            architecture: 'MixtralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 4096, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000006000, output: 0.0000006000},
        },
        {
            id: `${this.id}/mistralai/Mistral-7B-Instruct-v0.3`,
            name: 'Mistral v0.3 (7B) Instruct',
            description: '',
            architecture: 'MistralForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32768, embedding: 4096, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000002000, output: 0.0000002000},
        },
        {
            id: `${this.id}/nvidia/Llama-3.1-Nemotron-70B-Instruct-HF`,
            name: 'LLaMA 3.1 (70B) Nemotron Instruct Hugging Face',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 128256, embedding: 8192, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000008800, output: 0.0000008800},
        },
        {
            id: `${this.id}/perplexity-ai/r1-1776`,
            name: 'R1 1776',
            description: '',
            architecture: 'DeepseekV3ForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 129280, embedding: 7168, input: 163840, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000030000, output: 0.0000070000},
        },
        {
            id: `${this.id}/meta-llama/Llama-2-70b-hf`,
            name: 'LLaMA 2 (70B) Hugging Face',
            description: '',
            architecture: 'LlamaForCausalLM',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 32000, embedding: 8192, input: 4096, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000009000, output: 0.0000009000},
        },
        {
            id: `${this.id}/Qwen/Qwen2.5-VL-72B-Instruct`,
            name: 'Qwen VL 2.5 (72B) Instruct',
            description: '',
            architecture: 'Qwen2_5_VLForConditionalGeneration',
            capabilities: {
                embedding: false,
                tool_call: true,
                rerank: false,
                features: [],
                size: {vocab: 152064, embedding: 8192, input: 32768, output: 0},
                text: {input: true, output: true},
                image: {input: false, output: false},
                audio: {input: false, output: false},
                video: {input: false, output: false},
            },
            price: {input: 0.0000019500, output: 0.0000080000},
        },
    ];
    default = {
        baseURL: 'https://api.together.xyz/v1',
        pricingURL: 'https://together.ai/pricing',
        manageAPIKeysURL: 'https://api.together.ai/settings/api-keys',
        model: `mistralai/Mistral-7B-Instruct-v0.1`,
    };

    create(init: RequestInit = {}): OpenAIProvider {
        return createOpenAI({name: this.name, baseURL: this.baseUrl(init.baseURL), apiKey: this.apiKey(init.apiKey), headers: init.headers});
    }

    languageModel(model: string, init: RequestInit = {}): LanguageModel {
        return this.create(init)(model);
    }

    embeddingModel(model: string, init: RequestInit = {}): EmbeddingModel<string> {
        return this.create(init).textEmbeddingModel(model);
    }
}